version: v2
    
tasks:    
  deploy:
    runner:
      containers:
      - image: salesforce/salesforcedx:latest-rc-slim
    steps:
      - checkout
      - commands:
        - |
            export SFDX_DISABLE_DNS_CHECK=true
            # login 
            sfdx auth:jwt:grant -i ${CLIENT_ID} -f ./server.key -u ${USERNAME} -r ${INSTANCE_URL} -a ${ORG_NAME} -d -s
            # deploy
            sfdx force:source:push -u ${ORG_USERNAME}

            sfdx force:user:permset:assign -n ${ORG_USERNAME}
            sfdx force:user:permset:assign -n Walkthroughs

            sfdx force:data:tree:import -p ./data/sample-data-plan.json

            sfdx force:community:publish -n E-Bikes

