version: v2
    
tasks:    
  deploy:
    runner:
      containers:
      - image: salesforce/salesforcedx:latest-rc-slim
    steps:
      - checkout
      - commands:
        - |
            export SFDX_DISABLE_DNS_CHECK=true
            # login 
            sfdx auth:jwt:grant -i ${CLIENT_ID} -f ./server.key -u ${USERNAME} -r ${INSTANCE_URL} -a ${ORG_NAME} -d -s

            # delete the existing org
            # sfdx force:org:delete -p -u ebikes > out.log 2> /dev/null

            echo ${ORG_USERNAME}

            # create new org
            sfdx force:org:create -s -f config/project-scratch-def.json -a ${ORG_USERNAME}

            # deploy
            sfdx force:source:push -u ${ORG_USERNAME}

            sfdx force:user:permset:assign -n ${ORG_USERNAME}
            sfdx force:user:permset:assign -n Walkthroughs

            sfdx force:data:tree:import -p ./data/sample-data-plan.json

            sfdx force:community:publish -n E-Bikes

